#!/bin/sh

# Load NVM (Node Version Manager) if it exists
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  if [ -f ".nvmrc" ]; then
    nvm use
  else
    nvm use default
  fi
fi

# Run the validation scripts
npm run lint && npm run build && npm run test
